name: Continuous integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: Check if domains are sorted alphabetically
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check domain sorting
        run: |
          yq 'sort_by(.domain)' _data/sites.yml > _data/sorted.yml
          rm _data/sites.yml
          mv _data/sorted.yml _data/sites.yml
          git add .
          git diff
          git config --global user.email "github-action-bot@example.com"
          git config --global user.name "GitHub Action Bot"
          git commit -m "alphabatized _data/sites.yml" -a || echo "No changes to commit"
          git push